### ISSUE TITLE
When use toMoney() with zero as the first digit.

### ISSUE THREAD

**Issue by rmonteiro89** [BankFacil/vanilla-masker#46] opened 2015-07-18 18:00 UTC
When there is a zero as the first digit, it returns some non sense values.

Examples:
VMasker.toMoney(0100)
"0,64"

VMasker.toMoney(0770)
"5,04"

VMasker.toMoney(0010)
"0,08"

VMasker.toMoney(0770)
"5,04"

**Comment by leandroadacosta** [comment] 2015-07-18 18:15
gzuz crist. @caio-ribeiro-pereira did you see? hehe bizarro.

**Comment by caio-ribeiro-pereira** [comment] 2015-07-19 15:30
@rmonteiro89 thank you for hack the code kkkk, the first "0" is the bug, but you can simply sanitize left zeros to avoid this issue. Can you do that? Because I'm far from a computer to fix them

**Comment by duduribeiro** [comment] 2015-07-20 02:12
I think this is not a bug. 
https://en.wikipedia.org/wiki/Leading_zero
```
Many other programming languages, such as Python 2, Perl, Ruby, and the Unix shell bash also follow this specification for converting strings to numbers. As an example, "0020" does not represent 2010 ( 2×101 + 0×100 ), but rather 208 = 1610 ( 2×81 + 0×80 = 1×101 + 6×100 ). Decimal numbers written with leading zeros will be interpreted as octal by languages
```
It's not possible to get this value as string?
`VMasker.toMoney('0100')`

**Comment by leandroadacosta** [comment] 2016-02-13 20:06
@duduribeiro yes, it could be an alternative, good. so I will close this issue

**Closed by leandroadacosta** 2016-02-13 20:06 UTC
